### ISSUE TITLE
Cannot fetch

### ISSUE THREAD

**Issue by fchen09** [orchetect/OSCKit#13]
I suddenly cannot fetch the package from https://github.com/orchetect/OSCKit.
I saw there is a new file folder .github. is it the reason?

**Screenshots**
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/84703080/172041768-d9fdd8ef-0744-429a-8469-d535a15f22d1.png">

**Comment by orchetect** [comment]
Looks like an Xcode bug, I've seen something similar before with other repos.

What Xcode version are you on? I'm on 13.4 and it's working as expected.

Try removing the package, cancel out of the window, then re-add the package using the package URL.

![xcode-package-remove](https://user-images.githubusercontent.com/11605557/172065269-56dab0d7-fe7f-4a40-a162-17d4ad63a6a1.png)

![xcode-package](https://user-images.githubusercontent.com/11605557/172065226-4fd33b24-c9a9-472b-8ade-6a5ca5b90395.png)
