### ISSUE TITLE
Add example project using CocoaAsyncSocket

### ISSUE THREAD

**Issue by orchetect** [orchetect/OSCKit#16]
Add an additional example project demonstrating use of [CocoaAsyncSocket](https://github.com/robbiehanson/CocoaAsyncSocket).

**Comment by lysdexic-audio** [comment]
This would be great - any pointers here?

**Comment by orchetect** [comment]
I was planning on getting an example built really soon. In the mean time, for sending OSC this works:

```swift
import CocoaAsyncSocket
import OSCKit

let oscClient = GCDAsyncUdpSocket()

func oscClientSetup() throws {
    let data = OSCMessage(
        address: "/some/address/here",
        values: [.int32(1), .int32(2), .string("Test")]
    ).rawData
    
    oscClient.send(data,
                   toHost: "10.0.0.183",
                   port: 8000,
                   withTimeout: 5.0,
                   tag: 0)
}
```

**Comment by orchetect** [comment]
I was planning on getting an example built really soon. In the mean time, this is the basic implementation.

Just haven't done any usability tests to see if any particular options need to be set on the socket yet.

## Entitlements

If your app is for iOS you don't need to set any app entitlements. The user will be asked to allow local network connections the first time you open the UDP port(s).

Make sure if your app is for macOS and is sandboxed, you enable network connections:

![sandbox-network-connections](https://user-images.githubusercontent.com/11605557/182241598-284f4e60-c9e2-4eaf-87f6-57f9703f6794.png)

## Send

```swift
import CocoaAsyncSocket
import OSCKit

let oscClient = GCDAsyncUdpSocket()

func sendOSCMessage() {
    let data = OSCMessage(
        address: "/some/address/here",
        values: [.int32(1), .int32(2), .string("Test")]
    ).rawData
    
    oscClient.send(
        data,
        toHost: "127.0.0.1", // sends to local machine; change this to remote IP/hostname
        port: 8000, // standard remote OSC port but can be changed
        withTimeout: 5.0,
        tag: 0
    )
}
```

## Receive

```swift
let oscServer = GCDAsyncUdpSocket()

extension AppDelegate: GCDAsyncUdpSocketDelegate {
    func setupOSCServer() throws {
        oscServer.setDelegate(self)
        oscServer.setDelegateQueue(.global())
        try oscServer.bind(toPort: 8000) // standard local OSC port but can be changed
        try oscServer.beginReceiving()
    }
    
    func udpSocket(
        _ sock: GCDAsyncUdpSocket,
        didReceive data: Data,
        fromAddress address: Data,
        withFilterContext filterContext: Any?
    ) {
        guard let oscPayload = try? data.parseOSC() else {
            return
        }
        print(oscPayload) // handle received osc bundle or osc message here
    }
}
```

**Comment by orchetect** [comment]
I was planning on getting an example built really soon. In the mean time, this is the basic implementation.

Just haven't done any usability tests to see if any particular options need to be set on the socket yet.

## Entitlements

If your app is for iOS you don't need to set any app entitlements. The user will be asked to allow local network connections the first time you open the UDP port(s).

Make sure if your app is for macOS and is sandboxed, you enable network connections:

![sandbox-network-connections](https://user-images.githubusercontent.com/11605557/182241598-284f4e60-c9e2-4eaf-87f6-57f9703f6794.png)

## Send

```swift
import CocoaAsyncSocket
import OSCKit

let oscClient = GCDAsyncUdpSocket()

func sendOSCMessage() {
    let data = OSCMessage(
        address: "/some/address/here",
        values: [.int32(1), .int32(2), .string("Test")]
    ).rawData
    
    oscClient.send(
        data,
        toHost: "127.0.0.1", // sends to local machine; change this to remote IP/hostname
        port: 8000, // standard remote OSC port but can be changed
        withTimeout: 5.0,
        tag: 0
    )
}
```

## Receive

```swift
let oscServer = GCDAsyncUdpSocket()

extension AppDelegate: GCDAsyncUdpSocketDelegate {
    func setupOSCServer() throws {
        oscServer.setDelegate(self)
        oscServer.setDelegateQueue(.global())
        try oscServer.bind(toPort: 8000) // standard local OSC port but can be changed
        try oscServer.beginReceiving()
    }
    
    func udpSocket(
        _ sock: GCDAsyncUdpSocket,
        didReceive data: Data,
        fromAddress address: Data,
        withFilterContext filterContext: Any?
    ) {
        guard let oscPayload = try? data.parseOSC() else {
            return
        }
        print(oscPayload) // handle received osc bundle or osc message here
    }
}
```

**Comment by lysdexic-audio** [comment]
Nice one! Thanks Steffan 🙏 Will give this a shot later on!

www.lysdexic.com
www.linktr.ee/lysdexic

**Comment by orchetect** [comment]
I've also pushed a full example app to the repo:

https://github.com/orchetect/OSCKit/tree/main/Examples/CocoaAsyncSocketExample

I'm working on a 0.3.0 release soon so maybe just pull main branch for the time being.

**Comment by orchetect** [comment]
One thing I am likely planning to implement is optional networking modules.

ie:

This would import just the OSCKit library as it does now.

```swift
import OSCKit
```

But this would import OSCKit along with CocoaAsyncSocket as a dependency and some additional abstractions such as `OSCClient` and `OSCServer`. That way you just import this target and all the boilerplate would be done for you.

```swift
import OSCKitCAS
```
