### ISSUE TITLE
About local ip address

### ISSUE THREAD

**Issue by fchen09** [orchetect/OSCKit#26]
Hi, Thank you for the amazing toolkit!
My local ip is 10.0.4.10, another PC is 192.160.0.158
My ip 10.0.4.10 cannot be linked with OSCKit, but 192.160.0.158 can be linked.
Do you think it is possibly due to the OSCKit or it should have worked?

**Comment by orchetect** [comment]
I need more specific information in order to help. "Linked" can mean many different things. What exactly are you trying to do?

**Comment by fchen09** [comment]
I want to send osc signal from my iphone to a pc, UDP way, just send to PC,
single way.

    *func* startClient() {

        // OSC client setup

        oscClient = UDPClient(

            //host: "192.168.3.2",

            //host: "192.168.70.58",

            host: ip,

            port: 9000,

            queue: DispatchQueue.main//DispatchQueue.global(qos:
.userInteractive)

        )

        print("UDP client set up. \(ip)")

    }

Fu-Hao Chen
Ph.D.
Chemical Engineering, Syracuse University
Dr. Ian D Hosein's lab

**Comment by orchetect** [comment]
Are you using your own UDP framework?

Otherwise use `OSCClient()`, not UDPClient.

**Comment by fchen09** [comment]
Got it. Thank you so much!!!

Fu-Hao Chen
Ph.D.
Chemical Engineering, Syracuse University
Dr. Ian D Hosein's lab

**Comment by orchetect** [comment]
It may work. 11 values should fit within a UDP packet. I would not use an OSCBundle, just send one OSCMessage at a time.

If the packet is too large to send, it will just fail to send. You can try it and see if it works.

**Comment by fchen09** [comment]
Hi,
Since iOS14 requires some privacy settings, may I ask if there is any
bonjour service in OSCKit?
Or do I just need the "privacy-local network description"?

Since some of my customers said they are unable to link to local ip.
I am wondering if I missed some privacy settings.
But in my home wifi, it works very well.
Thank you!

Fu-Hao Chen
Ph.D.
Chemical Engineering, Syracuse University
Dr. Ian D Hosein's lab

**Comment by orchetect** [comment]
OSCKit does not contain any built-in bonjour services. It's possible in future it could be added.

If you are trying to communicate with devices on the local area network (LAN) then yes you will want the local network entitlement(s).

If your app is an iOS app, the OS will ask the user to allow the local connection and they must allow it or connections will be blocked and it won't ask them to allow it again.

To check this, in device Settings they would tap on the app and make sure "Local Network" is turned on, like this:

![iOS-App-Settings](https://user-images.githubusercontent.com/11605557/209504098-0a2c22dc-fa36-4e75-b1f5-2e0098fdb04e.jpeg)
