### ISSUE TITLE
Send and receive on same port (socket)?

### ISSUE THREAD

**Issue by orchetect** [orchetect/OSCKit#32]
### Transferred from Discussions

<div type='discussions-op-text'>

<sup>Originally posted by **alexford** April  6, 2023</sup>
Hello! This is a great library. I have a question about how I would achieve something I'm trying to do:

For my use case, I need to send and receive OSC messages from the same port. I am integrating with a family of mixers (Behringer XR series, as an example), that "respond" to some OSC messages by sending a message back to the _same port_ on the client that the original message was sent _from_.

So, I am trying to achieve this bidirectional communication by setting up both an `OSCClient` for sending and an `OSCServer` for receiving.

The issue I'm having is that when I set up an `OSCClient` from this library and send an OSC message, the outgoing port is randomly assigned by the OS. The mixer then responds back to that random port. I understand this is part of the behavior of `GCDAsyncUdpSocket` (and sockets in general), and a side effect of the two "sides" of this library each using their own socket.

I need an `OSCServer` to be listening on the same port that I send from, but I won't know that port until I send the first message. I have experimented a bit with trying to send an initial message, then interrogate the `udpClient` in the `OSCClient` to find the port, then start the `OSCServer` listening on that port. This required some minor modifications to `OSCKit`'s source to attempt. However, `OSCClient`'s use of `GCDAsyncUdpSocket` doesn't lend itself to the `enableReusePort` functionality (something about needing a delegate which the client does not use), so I couldn't get it to work cleanly and would have ended up making too many changes, so I came here for advice first.

**Essentially, I'm looking for a hybrid of an `OSCServer` and an `OSCClient` that sends and receives OSC messages over the same socket.** This is implemented in [another library, also called OSCKit](https://github.com/sammysmallman/OSCKit) as something [they call a "peer"](https://github.com/sammysmallman/OSCKit#step-1-4). However, I prefer the API, approach, and license of _this_ library, so I'm hoping it can be done here as well.

---

Looking at the code, it seems like this could be made to work by basically copying the `send` function from `OSCClient` into `OSCServer`, so that it sends over the same socket the server has already established.

Would it be strange to have `OSCServer` basically implement `OSCClient`, though?  I'm sure there's a better way to accomplish this without muddying the server/client dichotomy you've established here. Maybe a subclass of `OSCServer` that adds the send functionality? Looking for your feedback. I am happy to start a PR.

I'm very new to Swift _and_ UDP, so maybe I've missed something obvious, too!</div>

**Comment by orchetect** [comment]
@alexford I transferred the discussion to an issue here.

I built a new `OSCPeer` class. Check out the OSCKitPeerExample project from the [oscpeer](https://github.com/orchetect/OSCKit/tree/oscpeer) branch I pushed. 

This intrinsically allows port reuse and UDP broadcast, which I believe is necessary for the Behringer gear to respond correctly. The single object can send and receive and uses a common local and remote port number.

Let me know if this works or if anything needs adjustment.

**Comment by alexford** [comment]
Thank you! I will try this out as soon as I can.

Yes, that's the PDF I am working from as well.

**Comment by orchetect** [comment]
I've just now pushed some refactors to that branch, including the ability to pass `nil` as port number to `OSCPeer`. It then can automatically assign itself a free UDP port in the system without you having to supply one, and then uses that same port to send and receive.

**Comment by orchetect** [comment]
Since the X32 only expects OSC on port 10023, we shouldn't necessarily force the local port to also be 10023 because there's a chance it may not be available. I'm going to add hybrid functionality so that messages can be sent to a port number that differs from the local port number. The `send(_ oscObject:)` method can get a `port:` parameter where you could override the port number used.

**Comment by orchetect** [comment]
Ok now with the latest push to the branch, here's the invocation that I think will work for you:

```swift
let peer = OSCPeer(
    host: "192.168.0.2", // X32's host or IP address
    remotePort: 10023
) { message, _ in
        print("Received \(message)")
}

try peer.start()
```

**Comment by alexford** [comment]
This worked perfectly, using "Option 1".

_This_ use case doesn't require the `enableBroadcast` option on the socket, for what that's worth. I saw you opened #33, I agree it makes sense to make that its own option.

**Comment by orchetect** [comment]
Ok great 👍

I will probably implement broadcast as an option for the classes but defaulted to off. Will push release 0.5.0 soon and you’ll be able to switch onto that.

**Comment by orchetect** [comment]
Just some interesting observations while doing some further refactors.

Because `OSCPeer` internally uses a single socket object, port reuse isn't actually intrinsically needed, which makes sense. That's one benefit to having made a dedicated class for bidirectional communication. Further to that - I can, in fact, approximate the `OSCPeer` functionality with a tweaked version of `OSCClient` and `OSCServer` but they both **do** need to have port reuse enabled, since they each implement their own socket.

I am adding an `isIPv4BroadcastEnabled` property and an `isPortReuseEnabled` property to all the classes, both on an opt-in basis.

`OSCClient` gains the ability to optionally set its local port, enable broadcast, and set port reuse. In that case, a new `start()` method needs to be called on `OSCClient`, but only if any of those properties are modified. If instantiated simply as `OSCClient()` with no further changes it will behave the same as it did before - assigning a random local port and not needing `start()` to be called.

**Comment by orchetect** [comment]
Also upon reflection there is no implicit need to restrict `OSCPeer` to a single remote host/IP. Just like we're allowing the remote port to be overridden for each call to `send()`, it's entirely possible to allow the same override for remote host. The class still provides default host and remote port if not overridden in `send()`.

**Comment by orchetect** [comment]
I've renamed OSCPeer to OSCSocket, updated the example project (OSCKitSocketExample) and done the refactors for the other objects. Pushed to the `oscpeer` branch.

I've tested everything but it could use a bit more review before release.

**Comment by orchetect** [comment]
Release 0.5.0 is out with the new features. I'll close this thread since this is resolved.
