### ISSUE TITLE
Add 3rd-party network layer sample project

### ISSUE THREAD

**Issue by orchetect** [orchetect/OSCKit#4]
Add a sample project that demonstrates integrating with a 3rd-party network library to send and receive OSC.

Ideal candidates:

- Apple's [Network.framework](https://developer.apple.com/documentation/network)
  - [WWDC video](https://developer.apple.com/videos/play/wwdc2018/715) shows in-depth example code and usage
- [Swift-NIO](https://github.com/apple/swift-nio)

**Comment by JCurtisRMIT** [comment]
This would be really valuable. Just reading the readme for Swift-NIO makes my head spin. It’s preventing me from even trying your library

**Comment by orchetect** [comment]
Agreed - I did spent a little time with Swift-NIO in effort to get a sample project put together for OSCKit, but NIO is pretty complex and I didn't successfully get it working in the time I spent.

I may do a Network.framework demo because I've been using that in a number of my own apps and it's easier for the less tech-savvy.

**Comment by orchetect** [comment]
I added an example project using Network.framework in the `/Examples` folder.

On launch, it creates
- a server that listens for OSC messages on port 8000 and prints incoming messages to the console
- a client that can send OSC messages to a hard-coded IP address and port (you can change this in ViewController.swift)
- a window containing a button to send a test OSC message using the OSC client (message is hard-coded and editable in ViewController.swift)
